#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          3

yabai -m config active_window_border_color   0x99ecf0c1
yabai -m config normal_window_border_color   0x99555555
yabai -m config insert_feedback_color        0x99FF4250
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# ignore apps
yabai -m rule --add app="*" manage=off
yabai -m rule --add app="System Preferences" sticky=on layer=above manage=off
yabai -m rule --add app="Finder" sticky=on layer=above
yabai -m rule --add app="Telegram" sticky=on layer=above manage=off
yabai -m rule --add app="iTerm" sticky=on layer=above manage=off border=off
yabai -m rule --add app="1Password" sticky=on layer=above manage=off

# Status bar (simple-bar)
# yabai -m config external_bar all:32:0

# Чтобы лейблить рабочие столы
# yabai -m space 1 --label music
# yabai -m space 3 --label code
# yabai -m space 4 --label browser